/******************************* CUSTOM EO CLASS ******************************
 *
 * Generated by Athena Console. All Rights Reserved by Athena Source (c) 2007 - 2011.
 * www.athenaframework.org
 *
 * Generated on Feb 17, 2011 15:09:49 by Jack (Windows 7 6.1 [x86])
 * DB: MySQL 5.0[connection pool - driver class: com.mysql.jdbc.Driver, url: jdbc:mysql://localhost/employeedirMT?useUnicode=yes&characterEncoding=UTF-8, max active: 10, max idle: 0, max wait time: 5000, connection timeout: 300]
 *
 ******************************************************************************/

package com.sys;

import org.athenasource.framework.eo.core.baseclass.ext.IUser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sys.generated.User_EO;

// You may modify this file. It will not be overwritten in subsequent code generations.
/**
 * Represents a User
 */
public class User extends User_EO implements IUser {

	static final Logger log = LoggerFactory.getLogger(User.class);

	public User() {
		super();
	}

	public int getOrgId() {
		return getORG_ID();
	}

	public int getOuId() {
		// TODO Auto-generated method stub
		return 0;
	}

	public int getUserId() {
		return getUser_ID();
	}

}

