/******************************* CUSTOM EO CLASS ******************************
 *
 * Generated by Athena Console. All Rights Reserved by Athena Source (c) 2007 - 2011.
 * www.athenaframework.org
 *
 * Generated on Feb 17, 2011 14:58:04 by Jack (Windows 7 6.1 [x86])
 * DB: MySQL 5.0[connection pool - driver class: com.mysql.jdbc.Driver, url: jdbc:mysql://localhost/employeedirMT?useUnicode=yes&characterEncoding=UTF-8, max active: 10, max idle: 0, max wait time: 5000, connection timeout: 300]
 *
 ******************************************************************************/

package com.test;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.test.generated.Employee_EO;

// You may modify this file. It will not be overwritten in subsequent code generations. 
/**
 * Represents a Employee 
 */
public class Employee extends Employee_EO { 

	static final Logger log = LoggerFactory.getLogger(Employee.class);

	public Employee() {
		super();
	}

}

