/******************************* CUSTOM EO CLASS ******************************
 *
 * Generated by Athena Console. All Rights Reserved by Athena Source (c) 2007 - 2010.
 * www.athenaframework.org
 *
 * Generated on Nov 08, 2010 10:47:19 by Jack (Windows 7 6.1 [x86])
 * DB: MySQL 5.0[connection pool - driver class: com.mysql.jdbc.Driver, url: jdbc:mysql://localhost/employeedir?useUnicode=yes&characterEncoding=UTF-8, max active: 10, max idle: 5, max wait time: 5000, connection timeout: 300]
 *
 ******************************************************************************/

package com.test;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.test.generated.EmpProj_EO;

// You may modify this file. It will not be overwritten in subsequent code generations. 
/**
 * Represents a EmpProj 
 */
public class EmpProj extends EmpProj_EO { 

	static final Logger log = LoggerFactory.getLogger(EmpProj.class);

	public EmpProj() {
		super();
	}

}

