/******************************* CUSTOM EO CLASS ******************************
 *
 * Generated by Athena Console. All Rights Reserved by Athena Source (c) 2007 - 2011.
 * www.athenaframework.org
 *
 * Generated on Feb 21, 2011 14:13:16 by Jack (Windows 7 6.1 [x86])
 * DB: Derby 10.6[connection pool - driver class: org.apache.derby.jdbc.EmbeddedDriver, url: jdbc:derby:E:\INSPRISE\AthenaES\Tools\eclipse3.4.1\WORKSPACE\JavaEmployeeDir\empdb;create=true, max active: 10, max idle: 0, max wait time: 5000, connection timeout: 300]
 *
 ******************************************************************************/

package com.test;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.test.generated.Department_EO;

// You may modify this file. It will not be overwritten in subsequent code generations. 
/**
 * Represents a Department  - Department
 */
public class Department extends Department_EO { 

	static final Logger log = LoggerFactory.getLogger(Department.class);

	public Department() {
		super();
	}

}

