/******************************* CUSTOM EO CLASS ******************************
 *
 * Generated by Athena Console. All Rights Reserved by Athena Source (c) 2007 - 2011.
 * www.athenaframework.org
 *
 * Generated on Feb 21, 2011 14:13:16 by Jack (Windows 7 6.1 [x86])
 * DB: Derby 10.6[connection pool - driver class: org.apache.derby.jdbc.EmbeddedDriver, url: jdbc:derby:E:\INSPRISE\AthenaES\Tools\eclipse3.4.1\WORKSPACE\JavaEmployeeDir\empdb;create=true, max active: 10, max idle: 0, max wait time: 5000, connection timeout: 300]
 *
 ******************************************************************************/

package com.test
{
import org.athenasource.framework.eo.core.MetaDomain;

import com.test.generated.Employee_EO;

// You may modify this file. It will not be overwritten in subsequent code generations. 
/**
 * Represents a Employee  - Employee
 */
[RemoteClass(alias="com.test.Employee")]
public class Employee extends Employee_EO { 

	/**
	 * Creates a new instance and sets the entity type.
	 */
	public static function createNewInstance():Employee {
		var instance:Employee = new Employee();
		instance.entity = MetaDomain.getInstance().getEntityByName(Employee_EO.SYSTEM_NAME);
		return instance;
	}

} // end class
} // end package
